
export const VALIDATION_RULES = {
  USERNAME_MIN_LENGTH: 3,
  PASSWORD_MIN_LENGTH: 6,
  POST_TITLE_MIN_LENGTH: 3,
  POST_CONTENT_MIN_LENGTH: 20,
  FEED_DEFAULT_PAGE: 1,
  FEED_DEFAULT_LIMIT: 10,
  FEED_MAX_LIMIT: 50
} as const;
